// flow-typed signature: 244ba23d2bfa8f841c6456eeadb80a75
// flow-typed version: <<STUB>>/@msgpack/msgpack_v^1.12.2/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@msgpack/msgpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@msgpack/msgpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@msgpack/msgpack/dist.es5/msgpack' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist.es5/msgpack.min' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/CachedKeyDecoder' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/context' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/decode' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/decodeAsync' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/Decoder' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/encode' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/Encoder' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/ExtData' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/ExtensionCodec' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/timestamp' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/utils/int' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/utils/prettyByte' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/utils/stream' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/utils/typedArrays' {
  declare module.exports: any;
}

declare module '@msgpack/msgpack/dist/utils/utf8' {
  declare module.exports: any;
}

// Filename aliases
declare module '@msgpack/msgpack/dist.es5/msgpack.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist.es5/msgpack'>;
}
declare module '@msgpack/msgpack/dist.es5/msgpack.min.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist.es5/msgpack.min'>;
}
declare module '@msgpack/msgpack/dist/CachedKeyDecoder.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/CachedKeyDecoder'>;
}
declare module '@msgpack/msgpack/dist/context.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/context'>;
}
declare module '@msgpack/msgpack/dist/decode.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/decode'>;
}
declare module '@msgpack/msgpack/dist/decodeAsync.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/decodeAsync'>;
}
declare module '@msgpack/msgpack/dist/Decoder.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/Decoder'>;
}
declare module '@msgpack/msgpack/dist/encode.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/encode'>;
}
declare module '@msgpack/msgpack/dist/Encoder.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/Encoder'>;
}
declare module '@msgpack/msgpack/dist/ExtData.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/ExtData'>;
}
declare module '@msgpack/msgpack/dist/ExtensionCodec.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/ExtensionCodec'>;
}
declare module '@msgpack/msgpack/dist/index' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist'>;
}
declare module '@msgpack/msgpack/dist/index.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist'>;
}
declare module '@msgpack/msgpack/dist/timestamp.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/timestamp'>;
}
declare module '@msgpack/msgpack/dist/utils/int.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/utils/int'>;
}
declare module '@msgpack/msgpack/dist/utils/prettyByte.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/utils/prettyByte'>;
}
declare module '@msgpack/msgpack/dist/utils/stream.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/utils/stream'>;
}
declare module '@msgpack/msgpack/dist/utils/typedArrays.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/utils/typedArrays'>;
}
declare module '@msgpack/msgpack/dist/utils/utf8.js' {
  declare module.exports: $Exports<'@msgpack/msgpack/dist/utils/utf8'>;
}
