// flow-typed signature: 08dc9a376bea4784e794ed3c18a4e42e
// flow-typed version: <<STUB>>/node-discover_v^1.1.2/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-discover'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-discover' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-discover/examples/basic-advert' {
  declare module.exports: any;
}

declare module 'node-discover/examples/basic-argv' {
  declare module.exports: any;
}

declare module 'node-discover/examples/basic-self' {
  declare module.exports: any;
}

declare module 'node-discover/examples/basic' {
  declare module.exports: any;
}

declare module 'node-discover/examples/ddnode-test' {
  declare module.exports: any;
}

declare module 'node-discover/examples/ddnode' {
  declare module.exports: any;
}

declare module 'node-discover/examples/deventemitter-test' {
  declare module.exports: any;
}

declare module 'node-discover/examples/deventemitter-test2' {
  declare module.exports: any;
}

declare module 'node-discover/examples/deventemitter' {
  declare module.exports: any;
}

declare module 'node-discover/examples/master' {
  declare module.exports: any;
}

declare module 'node-discover/examples/redis' {
  declare module.exports: any;
}

declare module 'node-discover/examples/test-client' {
  declare module.exports: any;
}

declare module 'node-discover/examples/test-multicast' {
  declare module.exports: any;
}

declare module 'node-discover/examples/test-server' {
  declare module.exports: any;
}

declare module 'node-discover/examples/test' {
  declare module.exports: any;
}

declare module 'node-discover/lib/discover' {
  declare module.exports: any;
}

declare module 'node-discover/lib/leadership' {
  declare module.exports: any;
}

declare module 'node-discover/lib/network' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-discover/examples/basic-advert.js' {
  declare module.exports: $Exports<'node-discover/examples/basic-advert'>;
}
declare module 'node-discover/examples/basic-argv.js' {
  declare module.exports: $Exports<'node-discover/examples/basic-argv'>;
}
declare module 'node-discover/examples/basic-self.js' {
  declare module.exports: $Exports<'node-discover/examples/basic-self'>;
}
declare module 'node-discover/examples/basic.js' {
  declare module.exports: $Exports<'node-discover/examples/basic'>;
}
declare module 'node-discover/examples/ddnode-test.js' {
  declare module.exports: $Exports<'node-discover/examples/ddnode-test'>;
}
declare module 'node-discover/examples/ddnode.js' {
  declare module.exports: $Exports<'node-discover/examples/ddnode'>;
}
declare module 'node-discover/examples/deventemitter-test.js' {
  declare module.exports: $Exports<'node-discover/examples/deventemitter-test'>;
}
declare module 'node-discover/examples/deventemitter-test2.js' {
  declare module.exports: $Exports<'node-discover/examples/deventemitter-test2'>;
}
declare module 'node-discover/examples/deventemitter.js' {
  declare module.exports: $Exports<'node-discover/examples/deventemitter'>;
}
declare module 'node-discover/examples/master.js' {
  declare module.exports: $Exports<'node-discover/examples/master'>;
}
declare module 'node-discover/examples/redis.js' {
  declare module.exports: $Exports<'node-discover/examples/redis'>;
}
declare module 'node-discover/examples/test-client.js' {
  declare module.exports: $Exports<'node-discover/examples/test-client'>;
}
declare module 'node-discover/examples/test-multicast.js' {
  declare module.exports: $Exports<'node-discover/examples/test-multicast'>;
}
declare module 'node-discover/examples/test-server.js' {
  declare module.exports: $Exports<'node-discover/examples/test-server'>;
}
declare module 'node-discover/examples/test.js' {
  declare module.exports: $Exports<'node-discover/examples/test'>;
}
declare module 'node-discover/index' {
  declare module.exports: $Exports<'node-discover'>;
}
declare module 'node-discover/index.js' {
  declare module.exports: $Exports<'node-discover'>;
}
declare module 'node-discover/lib/discover.js' {
  declare module.exports: $Exports<'node-discover/lib/discover'>;
}
declare module 'node-discover/lib/leadership.js' {
  declare module.exports: $Exports<'node-discover/lib/leadership'>;
}
declare module 'node-discover/lib/network.js' {
  declare module.exports: $Exports<'node-discover/lib/network'>;
}
